//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pyExcel.WinApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pyExcel.WinApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Asterisk {
            get {
                object obj = ResourceManager.GetObject("Asterisk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проблема с Pyton в Excel.
        /// </summary>
        internal static string ErrorMessageCaption {
            get {
                return ResourceManager.GetString("ErrorMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неожиданная ошибка при работе приложения. Если проблема повториться сообщите о ней разработчикам..
        /// </summary>
        internal static string ErrorMessageDescriptionDefault {
            get {
                return ResourceManager.GetString("ErrorMessageDescriptionDefault", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Excel {
            get {
                object obj = ResourceManager.GetObject("Excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Exclamation {
            get {
                object obj = ResourceManager.GetObject("Exclamation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение….
        /// </summary>
        internal static string InformationMessageCaption {
            get {
                return ResourceManager.GetString("InformationMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книга Excel 97-2003 (*.xls)|*.xls.
        /// </summary>
        internal static string OpenFileExcelDialofFilter {
            get {
                return ResourceManager.GetString("OpenFileExcelDialofFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python (*.py)|*.py.
        /// </summary>
        internal static string OpenFilePythonDialofFilter {
            get {
                return ResourceManager.GetString("OpenFilePythonDialofFilter", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Python {
            get {
                object obj = ResourceManager.GetObject("Python", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрипт.
        /// </summary>
        internal static string PythonTabName {
            get {
                return ResourceManager.GetString("PythonTabName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Reload {
            get {
                object obj = ResourceManager.GetObject("Reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат.
        /// </summary>
        internal static string ResultTabName {
            get {
                return ResourceManager.GetString("ResultTabName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Run {
            get {
                object obj = ResourceManager.GetObject("Run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнить.
        /// </summary>
        internal static string RunButton {
            get {
                return ResourceManager.GetString("RunButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книга Excel 97-2003 (*.xls)|*.xls.
        /// </summary>
        internal static string SaveFileExcelDialofFilter {
            get {
                return ResourceManager.GetString("SaveFileExcelDialofFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установить проверку столбцов.
        /// </summary>
        internal static string SetCheckExcelColumnsType {
            get {
                return ResourceManager.GetString("SetCheckExcelColumnsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор строк.
        /// </summary>
        internal static string SetRowSelection {
            get {
                return ResourceManager.GetString("SetRowSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные.
        /// </summary>
        internal static string SourceTabName {
            get {
                return ResourceManager.GetString("SourceTabName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прервать.
        /// </summary>
        internal static string StopButton {
            get {
                return ResourceManager.GetString("StopButton", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Waiting {
            get {
                object obj = ResourceManager.GetObject("Waiting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение....
        /// </summary>
        internal static string WarningMessageCaption {
            get {
                return ResourceManager.GetString("WarningMessageCaption", resourceCulture);
            }
        }
    }
}
